image:
  file: .gitpod/Dockerfile

tasks:
  # Build to get everyting
  - init: ./gradlew build

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - richardwillis.vscode-gradle