# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.9

# Mod Properties
mod_version=1.2.2+1.21.4
maven_group=com.rouesvm
archives_base_name=serverbackpacks

# Dependencies
fabric_version=0.110.5+1.21.4
polymer=0.11.0+1.21.4-rc1
sgui=1.8.1+1.21.4

