# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check https://fabricmc.net/develop

minecraft_version=26.3-rc-2
loader_version=0.19.5
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_version=0.160.4+26.3

# Mod Properties
mod_version=1.6+26.3
maven_group=com.rouesvm
archives_base_name=serverbackpacks

# Dependencies

# https://maven.nucleoid.xyz/eu/pb4/polymer-core/
polymer=0.18.0+26.3-rc-1
# https://maven.nucleoid.xyz/eu/pb4/sgui/
sgui=2.2.0+26.3
# https://maven.nucleoid.xyz/xyz/nucleoid/server-translations-api/
server_translations=3.2.0+26.3
fabric_permissions_version=0.5.0

# https://maven.nucleoid.xyz/#/releases/eu/pb4/trinkets
trinkets=4.2.0+26.3
geyser=2.9.5-SNAPSHOT
