# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check https://fabricmc.net/develop

minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_version=0.144.3+26.1

# Mod Properties
mod_version=1.5.4+26.1
maven_group=com.rouesvm
archives_base_name=serverbackpacks

# Dependencies

# https://maven.nucleoid.xyz/eu/pb4/polymer-core/
polymer=0.16.0-pre.3+26.1
# https://maven.nucleoid.xyz/eu/pb4/sgui/
sgui=2.0.0-beta.2+26.1
# https://maven.nucleoid.xyz/xyz/nucleoid/server-translations-api/
server_translations=3.0.1+26.1
fabric_permissions_version=0.5.0

trinkets=4.0.0-alpha.1+26.1
geyser=2.9.5-SNAPSHOT
