name: Release
on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Set version in gradle.properties
        run: |
          TAG_VERSION=${{ github.event.release.tag_name }}
          MOD_VERSION=${TAG_VERSION#v}
          sed -i "s/^mod_version=.*$/mod_version=$MOD_VERSION/" gradle.properties
      - run: ./gradlew runDatagen build publishMods
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;!build/libs/*-dev.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
